      # You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:3

pipelines:
    branches:
      master:
        - step:
           script:
             - git remote add sync git@github.com:mozarkai/mozark-sdk-python.git
             - git checkout master
             - git pull
             - git push sync master

