      # You can specify a custom docker image from Docker Hub as your build environment.

pipelines:
  branches:
    master:
      - step:
          name: Just a simple echo!
          script:
            - echo "Hello world!"




#image: atlassian/default-image:3
#
#pipelines:
#  branches:
#    master:
#      - step:
#          script:
#            - git remote add sync git@github.com:mozark-ai/mozark-sdk-python.git
#            - git checkout master
#            - git pull
#            - git push sync master